AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
  - 'bin/console'

plugins:
- rubocop-rake
- rubocop-rspec

Metrics/MethodLength:
  CountAsOne: [ 'hash' ]

Style/AccessorGrouping:
  Enabled: false

# RSpec configuration
RSpec/MultipleDescribes:
  Enabled: false

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Max: 6

# Layout configuration
Layout/LineLength:
  Max: 130
